export const upcomingMovies = [
  {
    id: 1,
    title: "Tron: Ares",
    overview: "Sci-fi action sequel in the Tron franchise.",
    release_date: "2025-10-10",
    poster_path: "/tron-ares.jpg",
    backdrop_path: "/tron-ares-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 1200.5,
  },
  {
    id: 2,
    title: "The Conjuring: Last Rites",
    overview: "Final chapter of the paranormal Conjuring saga.",
    release_date: "2025-09-05",
    poster_path: "/conjuring-last-rites.jpg",
    backdrop_path: "/conjuring-last-rites-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 950.2,
  },
  {
    id: 3,
    title: "One Battle After Another",
    overview: "Paul Thomas Anderson’s IMAX drama starring Leonardo DiCaprio.",
    release_date: "2025-09-26",
    poster_path: "/one-battle-after-another.jpg",
    backdrop_path: "/one-battle-after-another-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 800.1,
  },
  {
    id: 4,
    title: "Predator: Badlands",
    overview: "New standalone Predator story starring Elle Fanning.",
    release_date: "2025-11-07",
    poster_path: "/predator-badlands.jpg",
    backdrop_path: "/predator-badlands-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 1005.6,
  },
  {
    id: 5,
    title: "Now You See Me: Now You Don't",
    overview: "Third installment in the heist-illusionist franchise.",
    release_date: "2025-11-14",
    poster_path: "/now-you-see-me-3.jpg",
    backdrop_path: "/now-you-see-me-3-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 860.4,
  },
  {
    id: 6,
    title: "Wicked: For Good",
    overview: "Musical finale of the Wicked two-part adaptation.",
    release_date: "2025-11-21",
    poster_path: "/wicked-for-good.jpg",
    backdrop_path: "/wicked-for-good-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 1320.7,
  },
  {
    id: 7,
    title: "Jingle Bell Heist",
    overview: "Christmas rom-com heist on Netflix starring Olivia Holt.",
    release_date: "2025-11-26",
    poster_path: "/jingle-bell-heist.jpg",
    backdrop_path: "/jingle-bell-heist-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 710.2,
  },
  {
    id: 8,
    title: "Wake Up Dead Man: A Knives Out Mystery",
    overview: "Knives Out franchise mystery from Rian Johnson.",
    release_date: "2025-12-12",
    poster_path: "/wake-up-dead-man.jpg",
    backdrop_path: "/wake-up-dead-man-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 1440.3,
  },
  {
    id: 9,
    title: "Avatar: Fire and Ash",
    overview: "Third Avatar film introducing the 'Ash People' tribe.",
    release_date: "2025-12-19",
    poster_path: "/avatar-fire-and-ash.jpg",
    backdrop_path: "/avatar-fire-and-ash-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 2000.9,
  },
  {
    id: 10,
    title: "Anaconda",
    overview:
      "Reimagined horror-comedy reboot starring Jack Black & Paul Rudd.",
    release_date: "2025-12-25",
    poster_path: "/anaconda.jpg",
    backdrop_path: "/anaconda-bg.jpg",
    vote_average: 0,
    vote_count: 0,
    popularity: 980.6,
  },
];
